version: '3.8'

services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: spring-relational-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '1432:5432'
