spring.application.name: spring-relational

spring:
  datasource:
    url: jdbc:postgresql://localhost:1432/spring-relational-db
    username: postgres
    password: postgres

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

logging:
  level:
    org.springframework.jdbc.core: trace